### ISSUE TITLE
Emoji display diferences between iOS and Android

### ISSUE THREAD

**Issue by grrrrr** [surespot/android#100]
When sending emoji from Android to iOS there a number that do not transfer correctly 

For example on iOS  the following appear when sent from android (assuming 7 emoji to a row)

row 2 emoji 6 - red cheeked smiley appears as alien
row 3 emoji 1 - red cheeked wide mouth smiley appears as alien
row 5 emoji 2 - crazy eyed appears as alien
row 5 emoji 3 - (repeat of row 3 emoji 1)

**Comment by akerbos** [comment]
I don't think Emoji issues are specific to Surespot; it's a feature of [Unicode plus your system font](http://en.wikipedia.org/wiki/Emoji), after all.

**Comment by akerbos** [comment]
Well, Surespot *does* overwrite system Emojis (for some reason) so the issue may apply after all.

My proposed solution is: drop own support of Emojis (which seems to be a waste of developer time and screen real estate) and just use what the platform provides.

**Comment by wp9015362** [comment]
+1

Apparently surespot seems to be using the "Phantom Open Emoji" set:

https://www.kickstarter.com/projects/374397522/phantom-open-emoji

I do not like them. And it is distracting that both conversation partners see different Emojis.

Also someone with iOS reported that when someone sends those built-in "Phantom Open Emoji"s from surespot-Android to surespot-iOS, surespot-iOS only displays black boxes instead of Emojis.

Here are also some related TextSecure issues which might be of interest regarding this topic:

https://github.com/WhisperSystems/TextSecure/issues/592
https://github.com/WhisperSystems/TextSecure/issues/827
https://github.com/WhisperSystems/TextSecure/pull/2302

**Comment by 2fours** [comment]
Version 70 now includes many more emoji.
