### ISSUE TITLE
Hide Emoji button or make it stop changing.

### ISSUE THREAD

**Issue by fallerOfFalls** [surespot/android#103]
I'm finding the emoji button very distracting. Could there be an option to hide it, or just stop it from being a different one every time? If it was always the same smiley face, I would get used to it and be able to ignore it.

**Comment by akerbos** [comment]
Agreed, this is annoying. We already have the Android emojis in the keyboard, anyway. (Do these work? Have to test.)

**Comment by wp9015362** [comment]
+1

The constant change is really distracting and doesn't make any sense at all IMHO.

It would be nice if it would be static instead. But it should not entirely be removed, because:

https://github.com/WhisperSystems/TextSecure/issues/827
https://github.com/WhisperSystems/TextSecure/pull/2302

An option to hide it would be okay of course.

**Comment by Sepero** [comment]
I try to share surespot with others, but the "changing emoticon" gives surespot a more amateur appearance.

**Comment by 2fours** [comment]
Version 70 does not change the icon anymore.
