### ISSUE TITLE
when surespot server is unreachable , login is not possible. messages can not be read offline

### ISSUE THREAD

**Issue by zoff99** [surespot/android#119]
when surespot servers are down (like they are now) then a login is not possible.
messages can not be accessed until servers are up again.

"Error logging in, please try again later."

this is not good. imagine when you are somewhere on a mountain (with no 3g connection available) and you startup your phone and try to read some important data in surespot (maybe some coordinates or something). you can not login and you have no chance to read messages offline.

also if your server should be shutdown permanently (i hope this will not happen), then all messages of all users are lost forever! they can never be accessed again.

(only info: surespot servers have been down 2 times already for a long period of time)

**Comment by zoff99** [comment]
no reply still on this bug!
if internet connection is turned off (or unavailable) you can NOT login to the app.
this is a critical bug.

or does the password get sent to your sever??

**Comment by SelfDestruct68** [comment]
Enable keychain

**Comment by zoff99** [comment]
thats no answer! i don't want a display lock.
it's a bug

**Comment by zoff99** [comment]
when you dont have internet.
+ you can not read older messages (if you are already logged in)
+ you can not delete a friend (if you are already logged in)
+ you can not login

**Comment by Dubz** [comment]
I know this is over a year old so this may not apply anymore, but I can read older messages just fine without using the keychain. Obviously you can't login or delete a friend if you aren't online because the messages aren't saved on your device for security reasons (if someone has the messages and key, they just need to bruteforce the password and everything can be opened), and obviously interacting with the server is required to actually delete someone.

As for exporting, you should do this immediately anyways. Failing to do so is taking a risk right there and your own fault.

If you're complaining that you want the app to be used without logging in or a screen lock, you obviously have no concern for security and should use something simpler and less secure. You can choose security or convenience, and this app gets as close to convenience as it can without sacrificing much (if any) security.
